channels:
  - conda-forge
  - qiime2
  - defaults
  - bioconda
dependencies:
  - python
  - scikit-bio
  - scikit-learn>=0.24
  - biom-format
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - qiime2
  - q2templates
  - q2-types
  - unifrac
  - pip
  - pip:
    - git+https://github.com/gwarmstrong/friendly-guacamole.git@main
