channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.8
  - scikit-bio
  - h5py<=3.1
  - scikit-learn>=0.24
  - biom-format
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - unifrac
  - pip
  - pip:
    - git+https://github.com/gwarmstrong/friendly-guacamole.git@main
    - nose
    - notebook
