name: q2-anomaly-detection CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: flake8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: lint
      run: |
        pip install -q flake8
        flake8

  build:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:        
        auto-update-conda: true
        python-version: 3.6
        activate-environment: test-q2-anomaly-detection
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env update --file ci/conda-requirements.yml
        pip install ".[test,analysis]"
    - name: Package Tests
      shell: bash -l {0}
      run: |
        nosetests
    - name: Notebook Tests
      shell: bash -l {0}
      run: |
        cd notebooks
        jupyter nbconvert --to python *.ipynb
        for f in *.py; do
          # remove magic commands
          sed -i '' '/get_ipython/d' $f
          python $f
        done
