name: q2-anomaly-detection CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: flake8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: lint
      run: |
        pip install -q flake8
        flake8

  build:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:        
        auto-update-conda: true
        python-version: 3.6 
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda create -n test-q2-anomaly-detection
        conda activate test-q2-anomaly-detection
        conda env update --file ci/conda-requirements.yml
        pip install ".[test]"

  package-tests:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.6
    - name: Package Tests
      shell: bash -l {0}
      run: |
        conda activate test-q2-anomaly-detection
        nosetests
