name: q2-anomaly-detection CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: flake8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: lint
      run: |
        pip install -q flake8
        flake8

  build:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      env:
        cache-name: cache-conda-env
      with:
        path: ~/conda_pkgs_dir
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ github.run_id }}
    - uses: conda-incubator/setup-miniconda@v2
      with:        
        auto-update-conda: true
        python-version: 3.6
        activate-environment: test-q2-anomaly-detection
        use-only-tar-bz2: true # this is needed for caching to work properly
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda create -n test-q2-anomaly-detection
        conda activate test-q2-anomaly-detection
        conda env update --file ci/conda-requirements.yml

  package-tests:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      env:
        cache-name: cache-conda-env
      with:
        path: ~/conda_pkgs_dir
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ github.run_id }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.6
        activate-environment: test-q2-anomaly-detection
        use-only-tar-bz2: true
    - name: Package Tests
      shell: bash -l {0}
      run: |
        pip install ".[test]"
        nosetests

  notebook-tests:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      env:
        cache-name: cache-conda-env
      with:
        path: ~/conda_pkgs_dir
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ github.run_id }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.6
        activate-environment: test-q2-anomaly-detection
        use-only-tar-bz2: true
    - name: Package Tests
      shell: bash -l {0}
      run: |
        pip install ".[analysis]"
        cd notebooks
        jupyter nbconvert --to python *.ipynb
        for f in *.py; do
          python $f
        done
